#ifndef __SOLID_TEXTURE_COLOR_NAMES_H__
#define __SOLID_TEXTURE_COLOR_NAMES_H__

enum SolidTextureColorNames {
    NO_TEXTURE = 0,
    COLOUR_TEXTURE = 1,
    BOZO_TEXTURE = 2,
    MARBLE_TEXTURE = 3,
    WOOD_TEXTURE = 4,
    CHECKER_TEXTURE = 5,
    CHECKER_TEXTURE_TEXTURE = 6,
    SPOTTED_TEXTURE = 7,
    AGATE_TEXTURE = 8,
    GRANITE_TEXTURE = 9,
    GRADIENT_TEXTURE = 10,
    IMAGE_MAP_TEXTURE = 11,
    ONION_TEXTURE = 15,
    LEOPARD_TEXTURE = 16,
    BRICK_TEXTURE = 17,
    MATERIAL_MAP_TEXTURE = 99
};

#endif
