#ifndef __SOLID_TEXTURE_BITMAP_INTERPOLATION_TYPES_H__
#define __SOLID_TEXTURE_BITMAP_INTERPOLATION_TYPES_H__

enum SolidTextureBitmapInterpolationTypes {
    NO_INTERPOLATION = 0,
    NEAREST_NEIGHBOR = 1,
    BILINEAR = 2,
    CUBIC_SPLINE = 3,
    NORMALIZED_DIST = 4
};

#endif
