#ifndef __SOLID_TEXTURE_COLOR_TEXTURES_H__
#define __SOLID_TEXTURE_COLOR_TEXTURES_H__

enum SolidTextureColorTextures {
    NO_TEXTURE = 0,
    COLOUR_TEXTURE = 1,
    BOZO_TEXTURE = 2,
    MARBLE_TEXTURE = 3,
    WOOD_TEXTURE = 4,
    CHECKER_TEXTURE = 5,
    CHECKER_TEXTURE_TEXTURE = 6,
    SPOTTED_TEXTURE = 7,
    AGATE_TEXTURE = 8,
    GRANITE_TEXTURE = 9,
    GRADIENT_TEXTURE = 10,
    IMAGEMAP_TEXTURE = 11,
    PAINTED1_TEXTURE = 12,
    PAINTED2_TEXTURE = 13,
    PAINTED3_TEXTURE = 14,
    ONION_TEXTURE = 15,
    LEOPARD_TEXTURE = 16,
    BRICK_TEXTURE = 17,
    MATERIAL_MAP_TEXTURE = 99
};

#endif
